---

- name: start tomcat
  service: name={{ service_name }} state=started
  sudo: yes

- name: stop tomcat
  service: name={{ service_name }} state=stopped
  sudo: yes

- name: restart tomcat
  service: name={{ service_name }} state=restarted
  sudo: yes

